# Generated by Django 3.2.13 on 2022-04-30 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Nationality',
                'verbose_name_plural': 'Nationality',
                'ordering': ['country', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=125)),
                ('roleDescription', models.CharField(blank=True, max_length=125, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ('role', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr')], default='Mr', max_length=4, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, default='profiles/default.png', help_text='upload image size less than 2.0MB', null=True, upload_to='profiles', verbose_name='Profile Image')),
                ('firstname', models.CharField(max_length=125, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=125, verbose_name='Lastname')),
                ('othername', models.CharField(blank=True, max_length=125, null=True, verbose_name='Othername (optional)')),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('Not Known', 'Not Known')], default='male', max_length=10, verbose_name='Gender')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email (optional)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='+06512345678', help_text='Enter number with Country Code Eg. +065 1234 5678', max_length=128, region=None, verbose_name='Phone Number (Example +6512345678)')),
                ('dateOfBirth', models.DateField(help_text='Enter mm/dd/yy Eg. 10/25/99', verbose_name='Date of Birth')),
                ('religion', models.CharField(choices=[('Buddhism', 'Buddhism'), ('No Religion', 'No Religion'), ('Islam', 'Islam'), ('Christian', 'Christian'), ('Taoism', 'Taoism'), ('Catholicism', 'Catholicism'), ('Hinduism', 'Hinduism'), ('Sikhism', 'Sikhism'), ('Other', 'Other')], default='No Religion', max_length=30, null=True, verbose_name='Religion')),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('address', models.CharField(blank=True, help_text='Enter address', max_length=125, null=True, verbose_name='Address')),
                ('education', models.CharField(choices=[('Primary Level', 'Primary School'), ('OLEVEL/NLevel', 'OLevel'), ('OLEVEL/NLevel', 'NLevel'), ('Tertiary', 'Bachelor Degree'), ('Tertiary', 'Master Degree'), ('Tertiary', 'Doctoral(PhD) Degree'), ('Tertiary', 'Diploma'), ('Other', 'Other')], default='Primary Level', help_text='highest educational standard ie. your last level of schooling', max_length=20, null=True, verbose_name='Education')),
                ('role', models.CharField(default=None, help_text='Enter Role Of Employee', max_length=125, null=True, verbose_name='Role')),
                ('startdate', models.DateField(help_text='Enter date of employement in mm/dd/yy Eg. 10/25/99"', null=True, verbose_name='Date of Employement ')),
                ('employeetype', models.CharField(choices=[('Full-Time', 'Full-Time'), ('Part-Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full-Time', max_length=15, null=True, verbose_name='Employee Type')),
                ('employeeid', models.CharField(blank=True, max_length=10, null=True, verbose_name='Employee ID Number')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False, help_text='button to toggle employee block and unblock', verbose_name='Is Blocked')),
                ('is_deleted', models.BooleanField(default=False, help_text='button to toggle employee deleted and undelete', verbose_name='Is Deleted')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=125, null=True, verbose_name='Name of Bank')),
                ('bankAccountNum', models.CharField(help_text='employee account number', max_length=30, null=True, verbose_name='Account Number')),
                ('salary', models.DecimalField(decimal_places=2, help_text='This is the initial salary of employee', max_digits=16, null=True, verbose_name='Starting Salary')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('employee', models.ForeignKey(help_text='select employee(s) to add bank account', null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.employee')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['-bank', '-bankAccountNum'],
            },
        ),
    ]
