# Generated by Django 3.2.13 on 2022-04-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(default=' ', max_length=64, unique=True),
        ),
    ]
