# Generated by Django 3.2.13 on 2022-05-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollSystem', '0004_auto_20220511_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_invoices', to='payrollSystem.person'),
        ),
    ]
