# Generated by Django 3.2.13 on 2022-05-13 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payrollSystem', '0005_alter_payroll_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Occupation',
            new_name='Roll',
        ),
        migrations.RenameField(
            model_name='roll',
            old_name='title',
            new_name='roll',
        ),
        migrations.RemoveField(
            model_name='person',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='person',
            name='title',
        ),
        migrations.AddField(
            model_name='person',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payrollSystem.roll', verbose_name='Roll'),
        ),
    ]
