# Generated by Django 3.2.13 on 2022-05-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payrollSystem', '0006_auto_20220513_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
