# Generated by Django 3.2.13 on 2022-05-13 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payrollSystem', '0007_alter_payroll_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
